import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

export default function (pi: ExtensionAPI) {
  // ───────────────────────────────────────────────────────────────
  // Helper: Create a pi extension file
  // ───────────────────────────────────────────────────────────────
  function scaffoldExtension(
    name: string,
    description: string,
    tools: Array<{
      name: string;
      description: string;
      parameters?: Record<string, { type: string; description: string; required?: boolean }>;
    }>,
    options: { outputDir?: string; withLifecycle?: boolean } = {},
  ): { filePath: string; content: string } {
    const toolRegistrations = tools
      .map((t) => {
        const paramEntries = t.parameters
          ? Object.entries(t.parameters).map(([key, val]) => {
              const typeboxType = val.type === "string" ? "Type.String()" : val.type === "number" ? "Type.Number()" : val.type === "boolean" ? "Type.Boolean()" : "Type.String()";
              return `      ${key}: ${typeboxType}${val.type === "string" ? `({ description: "${val.description}" })` : `({ description: "${val.description}" })`}`;
            })
          : [];
        const paramObj = paramEntries.length > 0 ? `Type.Object({\n${paramEntries.join(",\n")}\n    })` : "Type.Object({})";

        const requiredFields = t.parameters
          ? Object.entries(t.parameters)
              .filter(([, v]) => v.required)
              .map(([k]) => `"${k}"`)
          : [];
        const requiredArr = requiredFields.length > 0 ? `\n    required: [${requiredFields.join(", ")}],` : "";

        return `
  pi.registerTool({
    name: "${t.name}",
    label: "${t.name.charAt(0).toUpperCase() + t.name.slice(1)}",
    description: ${JSON.stringify(t.description)},
    promptSnippet: ${JSON.stringify(t.description.split(".")[0])},
    parameters: ${paramObj},${requiredArr}

    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Implement "${t.name}" logic
      return {
        content: [{ type: "text", text: \`Executed ${t.name} with: \${JSON.stringify(params)}\` }],
        details: { action: "${t.name}" },
      };
    },
  });`;
      })
      .join("\n");

    const lifecycleHooks = options.withLifecycle
      ? `
  // ── Lifecycle hooks ──────────────────────────────────────
  pi.on("session_start", async (_event, ctx) => {
    ctx.ui.notify("${name} extension loaded", "info");
  });

  pi.on("session_shutdown", async (_event, _ctx) => {
    // Cleanup state here
  });

  pi.on("tool_call", async (event, ctx) => {
    if (event.toolName === "bash" && event.input.command?.includes("dangerous")) {
      const ok = await ctx.ui.confirm("Hold up!", "Allow dangerous command?");
      if (!ok) return { block: true, reason: "Blocked by ${name}" };
    }
  });
`
      : "";

    const content = `import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

/**
 * ${name} — ${description}
 *
 * Generated by Darwin scaffold on ${new Date().toISOString().split("T")[0]}
 */
export default function (pi: ExtensionAPI) {
  // ── Tools ─────────────────────────────────────────────────
${toolRegistrations}
${lifecycleHooks}
  // ── Commands ──────────────────────────────────────────────
  pi.registerCommand("${name}", {
    description: ${JSON.stringify(description)},
    handler: async (args, ctx) => {
      ctx.ui.notify(\`${name}: \${args || "no args"}\`, "info");
    },
  });
}
`;

    const extDir = options.outputDir || resolve(process.cwd(), "pi/extensions");
    mkdirSync(extDir, { recursive: true });
    const filePath = join(extDir, `${name}.ts`);

    return { filePath, content };
  }

  // ───────────────────────────────────────────────────────────────
  // Helper: Create an E-service (Rust + Leptos + Axum)
  // ───────────────────────────────────────────────────────────────
  function scaffoldEService(
    name: string,
    description: string,
    options: {
      outputDir?: string;
      withAuth?: boolean;
      withDatabase?: boolean;
      port?: number;
    } = {},
  ): Array<{ filePath: string; content: string }> {
    const dir = options.outputDir || resolve(process.cwd(), name);
    const port = options.port || 8082;
    const kebab = name.toLowerCase().replace(/_/g, "-");
    const pascal = name
      .split(/[-_]/)
      .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
      .join("");
    const snake = name.replace(/-/g, "_").toLowerCase();

    const files: Array<{ filePath: string; content: string }> = [];

    // ── Cargo.toml ─────────────────────────────────────────────
    const dbDeps = options.withDatabase
      ? `sqlx = { version = "0.8.6", features = ["chrono", "runtime-tokio-rustls", "sqlite", "macros"], optional = true }`
      : "";
    const dbDepsDev = options.withDatabase
      ? `sqlx = { version = "0.8.6", features = ["chrono", "runtime-tokio-rustls", "sqlite"] }`
      : "";
    const authDeps = options.withAuth
      ? `jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"], optional = true }
argon2 = { version = "0.5.3", optional = true }`
      : "";
    const ssrFeatures = ["leptos/ssr", "leptos_axum", "leptos_router/ssr", "leptos_meta/ssr", "dep:axum", "dep:tokio", "dep:tower-http", "dep:tracing-subscriber"];
    if (options.withDatabase) ssrFeatures.push("dep:sqlx");
    if (options.withAuth) ssrFeatures.push("dep:jsonwebtoken", "dep:argon2");
    const ssrFeatStr = ssrFeatures.map((f) => `    "${f}"`).join(",\n");

    files.push({
      filePath: join(dir, "Cargo.toml"),
      content: `[package]
name = "${snake}"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.44"
uuid = { version = "1.23.0", features = ["v4", "js"] }
chrono = { version = "0.4.44", features = ["serde"] }
anyhow = "1.0.102"

leptos = { version = "0.7.8" }
leptos_axum = { version = "0.7.8", optional = true }
leptos_router = { version = "0.7.8" }
leptos_meta = { version = "0.7.8" }
wasm-bindgen = "0.2.118"
web-sys = { version = "0.3.77", features = ["Window", "Storage"] }
js-sys = "0.3.77"
console_error_panic_hook = "0.1.7"

axum = { version = "0.7.9", features = ["macros"], optional = true }
tokio = { version = "1.50.0", features = ["full"], optional = true }
tower-http = { version = "0.6.2", features = ["fs", "trace", "cors"], optional = true }
tracing-subscriber = { version = "0.3.23", optional = true }
http = { version = "1.2.0", optional = true }
${authDeps}
${dbDeps}

[dev-dependencies]
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
${dbDepsDev}

[features]
hydrate = ["leptos/hydrate"]
ssr = [
${ssrFeatStr},
]

[package.metadata.leptos]
output-name = "${snake}"
site-root = "target/site"
site-pkg-dir = "${snake}_pkg"
assets-dir = "public"
site-addr = "127.0.0.1:${port}"
reload-port = ${port + 2000}
env = "DEV"
bin-features = ["ssr"]
bin-target = "${snake}"
hydrate-features = ["hydrate"]
`,
    });

    // ── src/main.rs ────────────────────────────────────────────
    const dbInit = options.withDatabase
      ? `\n    // ── Database ────────────────────────────────────────\n    let db_url = std::env::var("DATABASE_URL").unwrap_or_else(|_| "sqlite:${snake}.db".to_string());\n    let conn_opts = sqlx::sqlite::SqliteConnectOptions::from_str(&db_url)?.create_if_missing(true);\n    let pool = sqlx::SqlitePoolOptions::new().connect_with(conn_opts).await?;\n    ${pascal}::DATABASE.set(pool.clone()).ok();`
      : "";

    files.push({
      filePath: join(dir, "src/main.rs"),
      content: `#![recursion_limit = "1024"]
#[cfg(feature = "ssr")]
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    use leptos::prelude::*;
    use leptos_axum::{generate_route_list, LeptosRoutes};
    use tower_http::services::ServeDir;
    use std::net::SocketAddr;
    use std::str::FromStr;
    use std::env;
    use ${snake}::app::{App, shell, AppState};${dbInit}

    tracing_subscriber::fmt::init();

    let conf = get_configuration(None).unwrap();
    let mut leptos_options = conf.leptos_options;
    leptos_options.site_pkg_dir = "${snake}_pkg".into();
    let fs_root = leptos_options.site_root.clone();
    let routes = generate_route_list(App);

    let state = AppState {
        leptos_options: leptos_options.clone(),
    };

    let app = axum::Router::new()
        .nest_service("/${kebab}/${snake}_pkg", ServeDir::new(format!("{}/${snake}_pkg", fs_root)))
        .nest_service("/${kebab}/favicon.ico", ServeDir::new("public/favicon.ico"))
        .leptos_routes(&state, routes, move || shell(leptos_options.clone()))
        .with_state(state);

    let host = env::var("SERVER_HOST").unwrap_or_else(|_| "0.0.0.0".to_string());
    let port = env::var("SERVER_PORT").unwrap_or_else(|_| "${port}".to_string());
    let addr = SocketAddr::from_str(&format!("{}:{}", host, port))?;

    tracing::info!("${name} v0.1.0 listening on http://{}", addr);
    let listener = tokio::net::TcpListener::bind(&addr).await?;
    axum::serve(listener, app).await?;
    Ok(())
}

#[cfg(not(feature = "ssr"))]
pub fn main() {}
`,
    });

    // ── src/lib.rs ─────────────────────────────────────────────
    const dbStatic = options.withDatabase
      ? `\n#[cfg(feature = "ssr")]\npub static DATABASE: std::sync::OnceLock<sqlx::SqlitePool> = std::sync::OnceLock::new();`
      : "";

    files.push({
      filePath: join(dir, "src/lib.rs"),
      content: `#![recursion_limit = "1024"]
pub mod app;
pub mod models;${dbStatic}

#[cfg(feature = "hydrate")]
#[wasm_bindgen::prelude::wasm_bindgen]
pub fn hydrate() {
    use app::*;
    use leptos::prelude::*;
    console_error_panic_hook::set_once();
    hydrate_body(App);
}
`,
    });

    // ── src/models.rs ──────────────────────────────────────────
    files.push({
      filePath: join(dir, "src/models.rs"),
      content: `use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Core model for ${name}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Item {
    pub id: String,
    pub title: String,
    pub created_at: chrono::NaiveDateTime,
}

impl Item {
    pub fn new(title: impl Into<String>) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            title: title.into(),
            created_at: chrono::Utc::now().naive_utc(),
        }
    }
}
`,
    });

    // ── src/app/mod.rs ─────────────────────────────────────────
    files.push({
      filePath: join(dir, "src/app/mod.rs"),
      content: `use leptos::prelude::*;
use leptos_meta::*;
use leptos_router::*;

#[cfg(feature = "ssr")]
#[derive(Debug, Clone)]
pub struct AppState {
    pub leptos_options: LeptosOptions,
}

#[cfg(feature = "ssr")]
impl std::fmt::Display for AppState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "AppState")
    }
}

#[cfg(feature = "ssr")]
impl axum::extract::FromRef<AppState> for LeptosOptions {
    fn from_ref(state: &AppState) -> Self {
        state.leptos_options.clone()
    }
}

/// Shell layout component
#[component]
pub fn shell(leptos_options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <AutoReload options=leptos_options.clone()/>
                <HydrationScripts options=leptos_options.clone()/>
                <link rel="icon" type="image/x-icon" href="/${kebab}/favicon.ico"/>
                <Meta name="description" content="${description}"/>
                <Title text="${name} — Easter Company"/>
            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}

/// Root application component
#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <Routes fallback=|| view! { "Page not found" }>
                <Route path="/${kebab}" view=HomePage/>
            </Routes>
        </Router>
    }
}

/// Homepage
#[component]
fn HomePage() -> impl IntoView {
    view! {
        <div style="padding: 2rem; font-family: system-ui, sans-serif;">
            <h1>{${pascal}::new().greeting()}</h1>
            <p>${description}</p>
            <p><em>Built with Leptos {leptos::version!()} + Axum</em></p>
        </div>
    }
}

struct ${pascal} { name: String }

impl ${pascal} {
    fn new() -> Self {
        Self { name: "${name}".to_string() }
    }
    fn greeting(&self) -> String {
        format!("Welcome to {} 🐣", self.name)
    }
}
`,
    });

    // ── public/ directory ──────────────────────────────────────
    files.push({
      filePath: join(dir, "public/favicon.ico"),
      content: "", // empty placeholder
    });

    // ── .env ───────────────────────────────────────────────────
    files.push({
      filePath: join(dir, ".env"),
      content: `# ${name}
SERVER_HOST=0.0.0.0
SERVER_PORT=${port}
${options.withDatabase ? `DATABASE_URL=sqlite:${snake}.db` : ""}
`,
    });

    // ── build_deploy.sh ────────────────────────────────────────
    files.push({
      filePath: join(dir, "build_deploy.sh"),
      content: `#!/bin/bash
# ${name} — Build & Deploy
# Easter Company — ${new Date().getFullYear()}

set -e

HOST="${name}.easter.company"
USER="deploy"
APP_DIR="/opt/${snake}"

echo "🔨 Building ${name}..."
cargo build --release --features ssr

echo "📦 Deploying to \${USER}@\${HOST}:\${APP_DIR}..."
rsync -avz --delete \\
    target/release/${snake} \\
    target/site/ \\
    \${USER}@\${HOST}:\${APP_DIR}/

echo "🔄 Restarting service..."
ssh \${USER}@\${HOST} "sudo systemctl restart ${snake}"

echo "✅ ${name} deployed successfully"
`,
    });

    return files;
  }

  // ───────────────────────────────────────────────────────────────
  // Tool: scaffold
  // ───────────────────────────────────────────────────────────────
  pi.registerTool({
    name: "scaffold",
    label: "Scaffold",
    description:
      "Generate boilerplate for Darwin extensions (TypeScript) or E-services (Rust/Leptos/Axum). " +
      "Use 'extension' mode to create a new pi coding agent tool. " +
      "Use 'e-service' mode to create a new Easter Company web service following EC conventions " +
      "(Axum + Leptos + SQLite + JWT auth).",
    promptSnippet: "Generate boilerplate code for extensions or services",
    promptGuidelines: [
      "Use scaffold when the user asks to create a new tool, extension, or Easter Company service.",
      "For extension mode, each tool definition should include name, description, and optional parameters.",
      "For e-service mode, specify whether auth/database features are wanted.",
    ],
    parameters: Type.Object({
      mode: Type.String({
        description: "What to scaffold: 'extension' for a pi tool extension, or 'e-service' for an EC Rust web service.",
      }),
      name: Type.String({
        description: "Name of the extension or service (e.g. 'weather', 'analytics-dashboard').",
      }),
      description: Type.String({
        description: "Description of what the extension or service does.",
      }),
      tools: Type.Optional(
        Type.Array(
          Type.Object({
            name: Type.String({ description: "Tool function name (e.g. 'get_weather')." }),
            description: Type.String({ description: "What this tool does." }),
            parameters: Type.Optional(
              Type.Record(Type.String(), Type.Object({
                type: Type.String({ description: "Parameter type: 'string', 'number', or 'boolean'." }),
                description: Type.String({ description: "What the parameter is for." }),
                required: Type.Optional(Type.Boolean({ description: "Whether parameter is required." })),
              }), { description: "Tool parameters as a record of name -> { type, description, required? }" })
            ),
          }),
          { description: "Array of tool definitions (for 'extension' mode)." }
        )
      ),
      withAuth: Type.Optional(
        Type.Boolean({ description: "Include JWT auth support? (e-service mode only, default: true)." })
      ),
      withDatabase: Type.Optional(
        Type.Boolean({ description: "Include SQLite database? (e-service mode only, default: true)." })
      ),
      port: Type.Optional(
        Type.Number({ description: "Service port (e-service mode only, default: 8082)." })
      ),
      outputDir: Type.Optional(
        Type.String({ description: "Output directory. Defaults to 'pi/extensions/' for extensions or './<name>/' for services." })
      ),
      withLifecycle: Type.Optional(
        Type.Boolean({ description: "Include session lifecycle hooks? (extension mode only)." })
      ),
    }),
    required: ["mode", "name", "description"],

    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      const {
        mode,
        name,
        description,
        tools = [],
        withAuth = true,
        withDatabase = true,
        port = 8082,
        outputDir,
        withLifecycle = false,
      } = params as {
        mode: string;
        name: string;
        description: string;
        tools?: Array<{
          name: string;
          description: string;
          parameters?: Record<string, { type: string; description: string; required?: boolean }>;
        }>;
        withAuth?: boolean;
        withDatabase?: boolean;
        port?: number;
        outputDir?: string;
        withLifecycle?: boolean;
      };

      if (mode === "extension") {
        // ── Scaffold a pi extension ──────────────────────────
        if (tools.length === 0) {
          return {
            content: [{ type: "text", text: "⚠️ No tools defined. Add at least one tool definition." }],
            isError: true,
            details: { error: "tools array empty" },
          };
        }

        const result = scaffoldExtension(name, description, tools, {
          outputDir: outputDir || join(ctx.cwd, "pi/extensions"),
          withLifecycle,
        });

        writeFileSync(result.filePath, result.content);

        // Also copy to pi's active extensions dir for immediate use
        const piExtDir = join(process.env.HOME || "/root", ".pi/agent/extensions");
        if (existsSync(piExtDir)) {
          writeFileSync(join(piExtDir, `${name}.ts`), result.content);
        }

        const toolList = tools.map((t) => `  - \`${t.name}\``).join("\n");

        const output = `## ✅ Extension Scaffolded: \`${name}\`

**File:** \`${result.filePath}\`
**Description:** ${description}
**Tools:**
${toolList}

### To activate:
Run \`/reload\` in pi to load the new extension and make the tools available.

### File contents:
\`\`\`typescript
${result.content}
\`\`\`
`;

        return {
          content: [{ type: "text", text: output }],
          details: {
            mode: "extension",
            filePath: result.filePath,
            tools: tools.map((t) => t.name),
          },
        };
      } else if (mode === "e-service") {
        // ── Scaffold an E-service ────────────────────────────
        const files = scaffoldEService(name, description, {
          outputDir: outputDir || join(ctx.cwd, name),
          withAuth,
          withDatabase,
          port,
        });

        // Write all files
        const written: string[] = [];
        for (const f of files) {
          const dir = f.filePath.substring(0, f.filePath.lastIndexOf("/"));
          mkdirSync(dir, { recursive: true });
          if (f.filePath.endsWith(".sh")) {
            writeFileSync(f.filePath, f.content, { mode: 0o755 });
          } else {
            writeFileSync(f.filePath, f.content);
          }
          written.push(f.filePath);
        }

        const featureList: string[] = [];
        if (withDatabase) featureList.push("SQLite via SQLx");
        if (withAuth) featureList.push("JWT auth via jsonwebtoken");
        featureList.push("Leptos SSR + Axum");

        const output = `## ✅ E-Service Scaffolded: \`${name}\`

**Directory:** \`${resolve(ctx.cwd, name)}\`
**Port:** ${port}
**Description:** ${description}

### Generated Files:
${written.map((f) => `- \`${f}\``).join("\n")}

### Features:
${featureList.map((f) => `- ${f}`).join("\n")}

### Next Steps:
\`\`\`bash
cd ${name}
cargo build --features ssr
cargo leptos serve
\`\`\`

### Architecture:
\`\`\`
${name}/
├── Cargo.toml          # Rust project with SSR/Hydrate features
├── .env                # Environment config
├── build_deploy.sh     # Deployment script
├── public/
│   └── favicon.ico
└── src/
    ├── main.rs         # Server entrypoint (Axum + Tokio)
    ├── lib.rs          # Library root + WASM hydrate
    ├── models.rs       # Data models (Serde)
    └── app/
        └── mod.rs      # Leptos app shell + routing + pages
\`\`\`
`;

        return {
          content: [{ type: "text", text: output }],
          details: {
            mode: "e-service",
            directory: resolve(ctx.cwd, name),
            files: written,
            features: featureList,
          },
        };
      } else {
        return {
          content: [
            {
              type: "text",
              text: `❌ Unknown mode: "${mode}". Use "extension" or "e-service".`,
            },
          ],
          isError: true,
          details: { error: `Unknown mode: ${mode}` },
        };
      }
    },
  });
}
